print("                                                              ")
print("                                                              ")
print("                                  _____________________       ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                 |      _________      |      ")
print("                                 |     |         |     |      ")
print("                                 |     |         |     |      ")
print("                                 |     |         |     |      ")
print("                                 |     |         |     |      ")
print("                                 |     |_________|     |      ")
print("                                 |                     |      ")
print("                                 |_____________________|      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                                       |      ")
print("                                  _____________________|      ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                 |\                   /|      ")
print("                                 | \                 / |      ")
print("                                 |  \               /  |      ")
print("                                 |   \             /   |      ")
print("                                 |    \           /    |      ")
print("                                 |     \         /     |      ")
print("                                 |      \       /      |      ")
print("                                 |       \     /       |      ")
print("                                 |        \   /        |      ")
print("                                 |         \ /         |      ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                 |                     |      ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                            /\                ")
print("                                           /  \               ")
print("                                          /    \              ")
print("                                         /      \             ")
print("                                        /        \            ")
print("                                       /          \           ")
print("                                      /            \          ")
print("                                     /              \         ")
print("                                    /                \        ")
print("                                   /                  \       ")
print("                                  /                    \      ")
print("                                 /_____________________ \     ")
print("                                /                        \    ")
print("                               /                          \   ")
print("                              /                            \  ")
print("                             /                              \ ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                                              ")
print("                                 ________________________     ")
print("                                |                        |    ")
print("                                |     ______________     |    ")
print("                                |    |              |    |    ")
print("                                |    |              |    |    ")
print("                                |    |______________|    |    ")
print("                                |________________________|    ")
print("                                                        /|    ")
print("                                                       / |    ")
print("                                                      /  |    ")
print("                                                     /   |    ")
print("                                                    /    |    ")
print("                                                   /     |    ")
print("                                                  /      |    ")
print("                                                 /       |    ")
print("                                                /        |    ")
print("                                               /         |    ")

